### PR TITLE
`curl` data without argument

### LINKED ISSUE #7: `curl` data without argument
Discussed in context of #5

### PR DESCRIPTION
**Pull request by jannis-baum**
Close #7

### CODE REVIEW

**Comment by jannis-baum** [comment]
Hey @tuurep this turned out easier than we thought :) Could you test that this also works on NeoVim?

I am not sure how long the file had to be do make it break before. I tested it now by duplicating our Markdown-basic test file to get to around 5000 lines and then the live reloading was still working. Duplicating it again made my whole Vim crash consistently, not sure if this is Vivify's fault but it probably doesn't matter anyways ^^

**Comment by tuurep** [comment]
Yeah this looks very promising, I had the old files lying around that I used to make the curl crash happen last time, and they all render now

But now the #10 changes are as if they weren't added:

Using this branch in nvim, and editing a 'regular' (non-huge) file, it seems like it's refreshing on CursorHold again, although this is on top of the current main

`:echo g:vivify_instant_refresh` gives `Undefined` which is intended, then it defaults to `1` in the plugin

Using viv `v0.2.1-2-aur`

This is pretty confusing.. Do you have an idea?

**Comment by tuurep** [comment]
I mean this commit doesn't really look like it's related to that

But I'm looking at the plugin pulled by `paq` and it has `configure-refresh-speed` + this commit on top. Hmm.

**Comment by tuurep** [comment]
**Abort Abort**

I had a scrap `vivify.vim` project folder in my `plugin` directory

Seems to be a cause of the above

Now I'll take another look :smile:

**Comment by tuurep** [comment]
So yes, overall this seems very good

I tried to find about where it stops fully functioning when duplicating the whole of `markdown-basic.md`

Same observation, at 5000 lines still working fine (refresh, cursor sync and all),

but can't go up to 6000 lines. So somewhere between 5000 and 6000 it's no longer syncing, but still scrollable on the browser.

Also if I have an individual `<p></p>` with 1500 lines of lorem ipsum in it, same happens there. But note: at 1000 lines of lorem ipsum the sync is still working fine :laughing: 

So to me seems like for sensible usage this is great.

I suppose it's possible to have a scenario where you work with 6000+ line md files, but I would definitely prioritize what we have here.

**Comment by tuurep** [comment]
Also there may have been cases where content refresh 'breaks' earlier than cursor sync does, if I'm not mistaken.

**Comment by tuurep** [comment]
I'd definitely approve this PR

And we could still make some fallback mechanisms for extreme scenarios I suppose, but it seems niche.

**Comment by jannis-baum** [comment]
Nice, thanks as always for the rigorous testing!

> I suppose it's possible to have a scenario where you work with 6000+ line md files, but I would definitely prioritize what we have here.

Yes I think the people that are working with 6000+ line md files have worse problems to deal with than auto-refresh not working😂

---

Will merge!

**Pull request merged**
