### PR TITLE
Sync cursor when first opening on viewer

### LINKED ISSUE #6: Sync cursor when first opening on viewer
Hey, I've identified that one of my most common habits of opening a viewer is reading a markdown document far down somewhere, and wanting to preview that same section.

But the way it's currently set up is that it opens at top, and I have focus back to (n)vim and do a `jk` or something.

Of course at first I thought it'd be as simple as doing `call vivify#sync_cursor()` after first opening viv like so:

```viml
function! vivify#open()
    " Note: nvim's jobstart doesn't use these opt keys
    call s:job_start(
        \ ['viv', expand('%:p')],
        \ {"in_io": "null", "out_io": "null", "err_io": "null"}
    \)
    call vivify#sync_cursor()
endfunction
```

However then it tries syncing cursor before the webpage has finished loading (I believe?)

Putting a 1 second sleep before sync_cursor works:

```viml
function! vivify#open()
    " Note: nvim's jobstart doesn't use these opt keys
    call s:job_start(
        \ ['viv', expand('%:p')],
        \ {"in_io": "null", "out_io": "null", "err_io": "null"}
    \)
    exec 'sleep'
    call vivify#sync_cursor()
endfunction
```

**So...**

Do you know of an easy way to do the sync_cursor at the exact time the webpage has finished loading?

Maybe I could find something in how Vim's job control works. Thought I'd ask if this is something you know off the top of your head.

Also, agree it's something that should be added?

### PR DESCRIPTION
**Pull request by jannis-baum**
Close #6

TODO before merging this:

- wait for https://github.com/jannis-baum/Vivify/pull/117 to be merged
- make a new release on main Vivify

### CODE REVIEW

**Comment by tuurep** [comment]
Perfect & fantastic

Gives me an **oftopic** thought though:

The way the cursor line is at the very bottom of the page feels pretty disorienting to me when opening

But what I'm getting to with this is that I wish the cursor sync could have a similar option to Vim's [scrolloff](https://vimhelp.org/options.txt.html#%27scrolloff%27), if you know what I mean

But of course it's more complicated because lines aren't a fixed size like in terminal

**Review by tuurep — APPROVED** [review]

**Comment by tuurep** [comment]
Yeah, that calls for a new issue

**Comment by jannis-baum** [comment]
> Yeah, that calls for a new issue

Agree! Feel free to open one :)

**Comment by tuurep** [comment]
Ok, I think we explained the feat quite well here so I just quoted us with the links and all.

**Comment by tuurep** [comment]
This requires a small change with `viv README.md:100` style scrolling added in https://github.com/jannis-baum/Vivify/pull/117 (and `-s` removed)

**Comment by jannis-baum** [comment]
> This requires a small change with `viv README.md:100` style scrolling added in [jannis-baum/Vivify#117](https://github.com/jannis-baum/Vivify/pull/117) (and `-s` removed)

I'll adjust this after we've merged the PR on main Vivify :)

**Comment by jannis-baum** [comment]
Hello @tuurep this should work now with the version of Vivify that's currently on main. Could you confirm?

**Comment by tuurep** [comment]
Yes it works

We've fixed all of my little usability gripes! Huge thanks

Well I still wish I could open an empty buffer as an empty markdown preview and start typing :smile: Btw I suspect this is because `file` shows the filetype of such file as `empty` instead of `markdown` (doesn't care about extension), nvim would show it as `markdown`

What do you think, is this fixable as well?

**Comment by jannis-baum** [comment]
> What do you think, is this fixable as well?

If I'm not completely mistesting this then it was a one-liner ^^ Check out https://github.com/jannis-baum/Vivify/pull/150

**Comment by jannis-baum** [comment]
I just remembered that this PR will break things if someone is on the `main` version of the plugin and the latest release of Vivify so I released Vivify v0.3.0. The release CI was of course broken again, eternal curse haha, but I think now I finally fixed it for good. Hope we never touch it again😂

**Pull request merged**
